<?php

/**
 * This is the model base class for the table "Page".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Page".
 * Columns in table "Page" available as properties of the model,
 * followed by relations of table "Page" available as properties of the model.
 *
 * @property integer   $id
 * @property string    $nom
 * @property Content[] $contents
 */
abstract class BasePage extends GxActiveRecord
{

    public static function model($className = __CLASS__)
    {

        return parent::model($className);
    }

    public function tableName()
    {

        return 'Page';
    }

    public static function label($n = 1)
    {

        return Yii::t('app', 'Page|Pages', $n);
    }

    public static function representingColumn()
    {

        return 'nom';
    }

    public function rules()
    {

        return array(
            array(
                'nom',
                'required'
            ),
            array(
                'nom',
                'length',
                'max' => 255
            ),
            array(
                'id, nom',
                'safe',
                'on' => 'search'
            ),
        );
    }

    public function relations()
    {

        return array(
            'contents' => array(
                self::HAS_MANY,
                'Content',
                'page_id'
            ),
        );
    }

    public function pivotModels()
    {

        return array();
    }

    public function attributeLabels()
    {

        return array(
            'id'       => Yii::t('app', 'ID'),
            'nom'      => Yii::t('app', 'Nom'),
            'contents' => null,
        );
    }

    public function search()
    {

        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nom', $this->nom, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}
